# .goreleaser.yaml
# k9s-style release configuration for k13d
version: 2

project_name: k13d

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - bash scripts/download-trivy.sh

builds:
  - id: k13d
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
    main: ./cmd/kube-ai-dashboard-cli/main.go
    binary: k13d
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

  # Separate build for Trivy-bundled archive (linux/darwin only)
  - id: k13d-trivy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/kube-ai-dashboard-cli/main.go
    binary: k13d
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: k13d-archive
    ids:
      - k13d
    formats:
      - tar.gz
    # k9s-style naming: k13d_v0.1.0_darwin_amd64.tar.gz, k13d_v0.1.0_darwin_arm64.tar.gz
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
      - docs/*
    # Wrap in directory for easier extraction
    wrap_in_directory: true

  # Trivy-bundled archive (linux/darwin only)
  - id: k13d-with-trivy
    ids:
      - k13d-trivy
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}-with-trivy_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - docs/*
      - src: .trivy-cache/{{ .Os }}_{{ .Arch }}/trivy
        dst: bin
        strip_parent: true
    wrap_in_directory: true

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: cloudbro-kube-ai
    name: k13d
  draft: false
  prerelease: auto
  mode: replace
  header: |
    Kubernetes AI Dashboard CLI
  footer: |
    **Full Changelog**: https://github.com/cloudbro-kube-ai/k13d/compare/{{ .PreviousTag }}...{{ .Tag }}
  name_template: "v{{.Version}}"

# Source code archive
source:
  enabled: true
  name_template: "{{ .ProjectName }}_v{{ .Version }}_source"
  formats:
    - tar.gz
